// actions/auto-map.ts
"use server";

import { db } from "@/db";
import { roleProfiles, organizationIntegrations } from "@/db/schema";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { MicrosoftGraphService } from "@/lib/infrastructure/microsoft-graph";

export async function autoMapEntraGroupAction(profileId: string) {
  try {
    // 1. Fetch Profile and Integration
    const profile = await db.query.roleProfiles.findFirst({
      where: eq(roleProfiles.id, profileId),
      with: { organization: true }
    });

    if (!profile) return { error: "Profile not found" };

    const integration = await db.query.organizationIntegrations.findFirst({
      where: eq(organizationIntegrations.orgId, profile.orgId)
    });

    if (!integration?.clientId || !integration?.clientSecret) {
      return { error: "Microsoft Integration missing." };
    }

    const msGraph = new MicrosoftGraphService(integration);

    // 2. Define the standard naming convention for our Groups
    const groupName = `Harmony - ${profile.name} (${profile.department})`;
    const mailNickname = `harmony_${profile.name.toLowerCase().replace(/[^a-z0-9]/g, '')}`;

    // 3. Search to see if the group already exists
    const existingGroup = await msGraph.findGroupByDisplayName(groupName);

    let entraGroupId = "";

    if (existingGroup) {
      // Group exists! Just grab the ID.
      entraGroupId = existingGroup.id;
    } else {
      // 4. Group doesn't exist? Create it as a Security Group!
      const newGroup = await msGraph.createSecurityGroup({
        description: `Auto-generated by Harmony OP for ${profile.name} role`,
        displayName: groupName,
        mailNickname: mailNickname,
      });
      entraGroupId = newGroup.id;
    }

    // 5. Save the ID to our Database so it is mapped forever
    await db.update(roleProfiles)
      .set({ entraGroupId, updatedAt: new Date() })
      .where(eq(roleProfiles.id, profileId));

    revalidatePath("/app/profiles");
    return { success: true };

  } catch (error) {
    console.error("Auto-map failed:", error);
    return { error: error instanceof Error ? error.message : "Failed to auto-map group" };
  }
}