// actions/auto-map.ts
"use server";

import { db } from "@/db";
import { roleProfiles, organizationIntegrations } from "@/db/schema";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";

export async function autoMapEntraGroupAction(profileId: string) {
  try {
    // 1. Fetch Profile and Integration
    const profile = await db.query.roleProfiles.findFirst({
      where: eq(roleProfiles.id, profileId),
      with: { organization: true }
    });

    if (!profile) return { error: "Profile not found" };

    const integration = await db.query.organizationIntegrations.findFirst({
      where: eq(organizationIntegrations.orgId, profile.orgId)
    });

    if (!integration?.clientId || !integration?.clientSecret) {
      return { error: "Microsoft Integration missing." };
    }

    // 2. Authenticate with Microsoft Graph
    const tokenRes = await fetch(`https://login.microsoftonline.com/${integration.tenantId}/oauth2/v2.0/token`, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: integration.clientId,
        scope: "https://graph.microsoft.com/.default",
        client_secret: integration.clientSecret,
        grant_type: "client_credentials",
      }),
    });
    const { access_token } = await tokenRes.json();
    if (!access_token) throw new Error("Failed to authenticate with Microsoft Graph");

    const headers = { 
      Authorization: `Bearer ${access_token}`, 
      "Content-Type": "application/json" 
    };

    // 3. Define the standard naming convention for our Groups
    const groupName = `Harmony - ${profile.name} (${profile.department})`;
    const mailNickname = `harmony_${profile.name.toLowerCase().replace(/[^a-z0-9]/g, '')}`;

    // 4. Search to see if the group already exists
    const searchRes = await fetch(`https://graph.microsoft.com/v1.0/groups?$filter=displayName eq '${groupName}'`, { headers });
    const searchData = await searchRes.json();

    let entraGroupId = "";

    if (searchData.value && searchData.value.length > 0) {
      // Group exists! Just grab the ID.
      entraGroupId = searchData.value[0].id;
    } else {
      // 5. Group doesn't exist? Create it as a Security Group!
      const createRes = await fetch(`https://graph.microsoft.com/v1.0/groups`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          description: `Auto-generated by Harmony OP for ${profile.name} role`,
          displayName: groupName,
          groupTypes: [], // Empty means Security Group
          mailEnabled: false,
          mailNickname: mailNickname,
          securityEnabled: true
        })
      });
      
      const newGroup = await createRes.json();
      if (newGroup.error) throw new Error(newGroup.error.message);
      entraGroupId = newGroup.id;
    }

    // 6. Save the ID to our Database so it is mapped forever
    await db.update(roleProfiles)
      .set({ entraGroupId, updatedAt: new Date() })
      .where(eq(roleProfiles.id, profileId));

    revalidatePath("/app/profiles");
    return { success: true };

  } catch (error: any) {
    console.error("Auto-map failed:", error);
    return { error: error.message || "Failed to auto-map group" };
  }
}